/**
 * FlashAlpha Historical SDK — public exports.
 */

export {
  FlashAlphaHistorical,
  formatAt,
  BASE_URL,
} from './client';
export type {
  AtLike,
  AtOptions,
  FlashAlphaHistoricalOptions,
  TickersOptions,
  OptionQuoteOptions,
  ExposureWithExpirationOptions,
  GexOptions,
  ZeroDteOptions,
  MaxPainOptions,
} from './client';

export {
  AuthenticationError,
  FlashAlphaHistoricalError,
  InsufficientDataError,
  InvalidAtError,
  NoCoverageError,
  NoDataError,
  RateLimitError,
  ServerError,
  SymbolNotFoundError,
  TierRestrictedError,
} from './errors';

export {
  Backtester,
  iterDays,
  iterMinutes,
  isTradingDay,
  replay,
} from './replay';
export type {
  BacktestStep,
  BacktesterOptions,
  IterDaysOptions,
  IterMinutesOptions,
  ReplayOptions,
  ReplayResult,
  Strategy,
} from './replay';

export type {
  ExposureSummaryExposures,
  ExposureSummaryHedgingEstimate,
  ExposureSummaryHedgingMove,
  ExposureSummaryInterpretation,
  ExposureSummaryResponse,
  ExposureSummaryZeroDte,
  // ── VRP ──
  VrpResponse,
  VrpCore,
  VrpDirectional,
  VrpTermItem,
  VrpGexConditioned,
  VrpVannaConditioned,
  VrpRegime,
  VrpStrategyScores,
  VrpMacro,
  // ── MaxPain ──
  MaxPainResponse,
  MaxPainDistance,
  MaxPainCurveRow,
  MaxPainOiRow,
  MaxPainByExpirationRow,
  MaxPainDealerAlignment,
  MaxPainExpectedMove,
  // ── StockSummary ──
  StockSummaryResponse,
  StockSummaryPrice,
  StockSummarySkew25d,
  StockSummaryIvTermItem,
  StockSummaryVolatility,
  StockSummaryOptionsFlow,
  StockSummaryInterpretation,
  StockSummaryHedgingMove,
  StockSummaryHedgingEstimate,
  StockSummaryZeroDte,
  StockSummaryTopStrike,
  StockSummaryExposure,
  StockSummaryMacroIndex,
  StockSummaryVixTermLevels,
  StockSummaryVixTermStructure,
  StockSummaryVixFutures,
  StockSummaryFearAndGreed,
  StockSummaryMacro,
  // ── Narrative ──
  NarrativeResponse,
  Narrative,
  NarrativeData,
  NarrativeOiChange,
  // ── ExposureLevels ──
  ExposureLevelsResponse,
  ExposureLevels,
  // ── ZeroDte ──
  ZeroDteResponse,
  ZeroDteRegime,
  ZeroDteExposures,
  ZeroDteExpectedMove,
  ZeroDtePinComponents,
  ZeroDtePinRisk,
  ZeroDteHedgingBucket,
  ZeroDteHedging,
  ZeroDteDecay,
  ZeroDteVolContext,
  ZeroDteFlow,
  ZeroDteLevels,
  ZeroDteLiquidity,
  ZeroDteMetadata,
  ZeroDteStrike,
  // ── Volatility ──
  VolatilityResponse,
  VolatilityRealizedVol,
  VolatilityIvRvSpreads,
  VolatilitySkewProfile,
  VolatilityTermStructure,
  VolatilityIvDispersion,
  VolatilityGexBucket,
  VolatilityThetaBucket,
  VolatilityPutCallByExpiry,
  VolatilityPutCallByMoneyness,
  VolatilityPutCallProfile,
  VolatilityOiConcentration,
  VolatilityHedgingScenario,
  VolatilityLiquidity,
  // ── AdvVolatility ──
  AdvVolatilityResponse,
  AdvVolatilitySviParameters,
  AdvVolatilityForwardPrice,
  AdvVolatilityTotalVarianceSurface,
  AdvVolatilityArbitrageFlag,
  AdvVolatilityVarianceSwapFairValue,
  AdvVolatilityGreekSurface,
  AdvVolatilityGreeksSurfaces,
  // ── Surface ──
  SurfaceResponse,
  // ── Exposure (GEX/DEX/VEX/CHEX) ──
  GexResponse,
  GexStrike,
  DexResponse,
  DexStrike,
  VexResponse,
  VexStrike,
  ChexResponse,
  ChexStrike,
  // ── Account / Reference Data / Health / Screener ──
  AccountResponse,
  TickersResponse,
  SymbolsResponse,
  OptionsMetaResponse,
  OptionsMetaExpiration,
  HealthResponse,
  ScreenerResponse,
  ScreenerMeta,
} from './types';
